import React, {createContext, useCallback, useContext, useEffect, useMemo, useReducer, useRef, useState} from 'react';
import {ActivityIndicator, Alert, FlatList, Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TextInput, View} from 'react-native';
import {cartReducer, initialCart} from './src/reducers/cartReducer';
import {useDebounce} from './src/hooks/useDebounce';
import {useForm} from './src/hooks/useForm';
import menu from './src/data/menu';
import users from './src/data/users';

const AuthContext=createContext(null); const ThemeContext=createContext(null); const CartContext=createContext(null);
const useAuth=()=>useContext(AuthContext); const useTheme=()=>useContext(ThemeContext); const useCart=()=>useContext(CartContext);

function AuthProvider({children}){const [user,setUser]=useState(null); const login=useCallback((u)=>setUser(u),[]); const logout=useCallback(()=>setUser(null),[]); return <AuthContext.Provider value={{user,login,logout}}>{children}</AuthContext.Provider>}
function ThemeProvider({children}){const [isDark,toggle]=useReducer(v=>!v,false); const colors=isDark?dark:light; return <ThemeContext.Provider value={{isDark,toggle,colors}}>{children}</ThemeContext.Provider>}
function CartProvider({children}){const [state,dispatch]=useReducer(cartReducer,initialCart); return <CartContext.Provider value={{state,dispatch}}>{children}</CartContext.Provider>}

const light={bg:'#F7F7F5',card:'#FFFFFF',text:'#1F2937',muted:'#6B7280',accent:'#C2410C',border:'#E5E7EB',danger:'#B91C1C'};
const dark={bg:'#111827',card:'#1F2937',text:'#F9FAFB',muted:'#9CA3AF',accent:'#FB923C',border:'#374151',danger:'#F87171'};

function Login(){const {login}=useAuth(); const {colors}=useTheme(); const [signup,setSignup]=useState(false); const [show,setShow]=useState(false); const [busy,setBusy]=useState(false); const [role,setRole]=useState('customer');
 const validate=v=>{const e={}; if(!/^\S+@\S+\.\S+$/.test(v.email))e.email='Enter a valid email'; if(v.password.length<8||!/\d/.test(v.password))e.password='8+ characters and one digit'; if(signup&&v.password!==v.confirm)e.confirm='Passwords do not match'; return e};
 const form=useForm({email:'',password:'',confirm:'',name:''},validate);
 const submit=async()=>{const e=form.validate(form.values); if(Object.keys(e).length){form.setErrors(e);return;} setBusy(true); await new Promise(r=>setTimeout(r,600)); const u=users.find(x=>x.email.toLowerCase()===form.values.email.toLowerCase()&&x.password===form.values.password); setBusy(false); if(u){login({...u,role});} else if(signup){login({id:Date.now(),name:form.values.name||'New Customer',email:form.values.email,role});} else Alert.alert('Login failed','Use the mock credentials shown below.');};
 return <SafeAreaView style={[s.safe,{backgroundColor:colors.bg}]}><ScrollView contentContainerStyle={s.center}><Text style={[s.logo,{color:colors.accent}]}>🍽️ Feastly</Text><Text style={[s.h1,{color:colors.text}]}>{signup?'Create account':'Welcome back'}</Text>{signup&&<Input label="Full name" value={form.values.name} onChangeText={v=>form.handleChange('name',v)} colors={colors}/>}<Input label="Email" value={form.values.email} onChangeText={v=>form.handleChange('email',v)} colors={colors} keyboardType="email-address"/><Input label="Password" value={form.values.password} onChangeText={v=>form.handleChange('password',v)} colors={colors} secureTextEntry={!show}/>{signup&&<Input label="Confirm password" value={form.values.confirm} onChangeText={v=>form.handleChange('confirm',v)} colors={colors} secureTextEntry={!show}/>}<Pressable onPress={()=>setShow(!show)}><Text style={{color:colors.accent,marginBottom:12}}>{show?'Hide password':'Show password'}</Text></Pressable>{signup&&<View style={s.row}><RoleButton title="Customer" active={role==='customer'} onPress={()=>setRole('customer')} colors={colors}/><RoleButton title="Manager" active={role==='manager'} onPress={()=>setRole('manager')} colors={colors}/></View>}<Pressable disabled={busy} onPress={submit} style={[s.button,{backgroundColor:colors.accent,opacity:busy?.6:1}]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>{signup?'Sign Up':'Login'}</Text>}</Pressable><Pressable onPress={()=>setSignup(!signup)}><Text style={{color:colors.accent,marginTop:16}}>{signup?'Already have an account? Login':'New user? Create an account'}</Text></Pressable><Text style={[s.note,{color:colors.muted}]}>Demo: customer@example.com / Customer123 · manager@example.com / Manager123</Text></ScrollView></SafeAreaView>}
function Input({label,colors,...p}){return <View style={{width:'100%',marginBottom:10}}><Text style={{color:colors.muted,marginBottom:4}}>{label}</Text><TextInput {...p} placeholderTextColor={colors.muted} style={[s.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.card}]}/></View>}
function RoleButton({title,active,onPress,colors}){return <Pressable onPress={onPress} style={[s.role,{borderColor:active?colors.accent:colors.border,backgroundColor:colors.card}]}><Text style={{color:colors.text}}>{title}</Text></Pressable>}

function MainApp(){const {user,logout}=useAuth(); const {isDark,toggle,colors}=useTheme(); const {state,dispatch}=useCart(); const [tab,setTab]=useState(user?.role==='manager'?'dashboard':'menu'); const [query,setQuery]=useState(''); const [category,setCategory]=useState('All'); const [sort,setSort]=useState('name'); const [favs,setFavs]=useState([]); const [orders,setOrders]=useState([]); const [reservations,setReservations]=useState([]); const [selected,setSelected]=useState(null); const [loading,setLoading]=useState(true); const debounced=useDebounce(query,400); const listRef=useRef(null); const searchRef=useRef(null); const renderCount=useRef(0); renderCount.current+=1;
 useEffect(()=>{const t=setTimeout(()=>setLoading(false),500);return()=>clearTimeout(t)},[]);
 const filtered=useMemo(()=>menu.filter(x=>(category==='All'||x.category===category)&&x.name.toLowerCase().includes(debounced.toLowerCase())).sort((a,b)=>sort==='priceLow'?a.price-b.price:sort==='priceHigh'?b.price-a.price:a.name.localeCompare(b.name)),[category,debounced,sort]);
 const add=useCallback((item)=>dispatch({type:'ADD_ITEM',payload:item}),[dispatch]); const toggleFav=useCallback(id=>setFavs(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]),[]);
 const checkout=()=>{if(!state.items.length){Alert.alert('Cart empty');return;} const order={id:'ORD-'+Math.floor(Math.random()*9000+1000),items:state.items,total:state.items.reduce((a,x)=>a+x.price*x.quantity,0),status:'Pending',type:'Takeaway',timestamp:Date.now()};setOrders(v=>[order,...v]);dispatch({type:'CLEAR_CART'});setTab('orders');setSelected(order.id);};
 useEffect(()=>{if(!orders.length)return; const t=setInterval(()=>setOrders(v=>v.map(o=>{const age=(Date.now()-o.timestamp)/1000; const status=age>=30?'Served':age>=20?'Ready':age>=10?'Preparing':'Pending'; return {...o,status}})),1000);return()=>clearInterval(t)},[orders.length]);
 const categories=['All',...new Set(menu.map(x=>x.category))];
 if(loading)return <SafeAreaView style={[s.safe,{backgroundColor:colors.bg}]}><ActivityIndicator size="large" color={colors.accent}/><Text style={{color:colors.text,textAlign:'center'}}>Loading local data…</Text></SafeAreaView>;
 const screen=tab==='menu'?<Menu colors={colors} categories={categories} category={category} setCategory={setCategory} filtered={filtered} add={add} favs={favs} toggleFav={toggleFav} query={query} setQuery={setQuery} searchRef={searchRef} listRef={listRef} renderCount={renderCount.current} sort={sort} setSort={setSort}/>:tab==='cart'?<Cart colors={colors} state={state} dispatch={dispatch} checkout={checkout}/>:tab==='reserve'?<Reserve colors={colors} reservations={reservations} setReservations={setReservations}/>:tab==='orders'?<Orders colors={colors} orders={orders}/>:tab==='profile'?<Profile colors={colors} user={user} isDark={isDark} toggle={toggle} logout={logout}/>:<Dashboard colors={colors} orders={orders} setOrders={setOrders}/>;
 return <SafeAreaView style={[s.safe,{backgroundColor:colors.bg}]}><View style={{flex:1}}>{screen}</View><View style={[s.tabs,{backgroundColor:colors.card,borderColor:colors.border}]}>{(user.role==='customer'?['menu','cart','reserve','orders','profile']:['dashboard','orders','profile']).map(x=><Pressable key={x} onPress={()=>setTab(x)} style={s.tab}><Text style={{fontSize:20}}>{x==='menu'?'🍴':x==='cart'?'🛒':x==='reserve'?'📅':x==='orders'?'📦':x==='profile'?'👤':'📊'}</Text><Text style={{fontSize:11,color:tab===x?colors.accent:colors.muted}}>{x}</Text></Pressable>)}</View></SafeAreaView>}
function Header({title,colors}){return <View style={s.header}><Text style={[s.h2,{color:colors.text}]}>{title}</Text></View>}
function Menu({colors,categories,category,setCategory,filtered,add,favs,toggleFav,query,setQuery,searchRef,listRef,renderCount,sort,setSort}){const [recent,setRecent]=useState([]); const doSearch=v=>{setQuery(v);if(v.trim())setRecent(r=>[v,...r.filter(x=>x!==v)].slice(0,5))};return <View style={{flex:1}}><Header title={`Menu (${filtered.length})`} colors={colors}/><View style={{paddingHorizontal:14}}><TextInput ref={searchRef} value={query} onChangeText={doSearch} placeholder="Search menu…" placeholderTextColor={colors.muted} style={[s.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.card}]}/><View style={s.chips}>{categories.map(c=><Pressable key={c} onPress={()=>setCategory(c)} style={[s.chip,{backgroundColor:category===c?colors.accent:colors.card,borderColor:colors.border}]}><Text style={{color:category===c?'#fff':colors.text}}>{c}</Text></Pressable>)}</View><View style={s.row}><Text style={{color:colors.muted}}>Sort:</Text>{[['name','A-Z'],['priceLow','Low'],['priceHigh','High']].map(([v,l])=><Pressable key={v} onPress={()=>setSort(v)}><Text style={{color:sort===v?colors.accent:colors.text,marginLeft:12}}>{l}</Text></Pressable>)}</View><Text style={{color:colors.muted,fontSize:11}}>Render debug: {renderCount} · Debounce: 400ms</Text></View>{recent.length>0&&!query&&<View style={{padding:10}}><Text style={{color:colors.muted}}>Recent: {recent.join(' · ')}</Text></View>}<FlatList ref={listRef} data={filtered} keyExtractor={x=>String(x.id)} onScroll={e=>{if(e.nativeEvent.contentOffset.y>300){} }} scrollEventThrottle={16} contentContainerStyle={{padding:14}} renderItem={({item})=><View style={[s.card,{backgroundColor:colors.card,borderColor:colors.border,opacity:item.isAvailable?1:.55}]}><View style={{flex:1}}><Text style={[s.bold,{color:colors.text}]}>{item.isSpecial?'⭐ ':''}{item.name}</Text><Text style={{color:colors.muted}}>{item.description}</Text><Text style={{color:colors.accent,fontWeight:'700'}}>Rs. {item.price}</Text></View><View><Pressable onPress={()=>toggleFav(item.id)}><Text style={{fontSize:22}}>{favs.includes(item.id)?'❤️':'♡'}</Text></Pressable><Pressable disabled={!item.isAvailable} onPress={()=>add(item)} style={[s.smallButton,{backgroundColor:colors.accent}]}><Text style={{color:'#fff'}}>{item.isAvailable?'Add':'Unavailable'}</Text></Pressable></View></View>)}/></View>}
function Cart({colors,state,dispatch,checkout}){return <ScrollView contentContainerStyle={{padding:14}}><Header title={`Cart (${state.items.length})`} colors={colors}/>{state.items.map(x=><View key={x.id} style={[s.card,{backgroundColor:colors.card,borderColor:colors.border}]}><View style={{flex:1}}><Text style={[s.bold,{color:colors.text}]}>{x.name}</Text><Text style={{color:colors.muted}}>Rs. {x.price} × {x.quantity}</Text></View><View style={s.row}><Pressable onPress={()=>dispatch({type:'DECREMENT',payload:x.id})}><Text style={s.qty}>−</Text></Pressable><Text style={{color:colors.text,padding:8}}>{x.quantity}</Text><Pressable onPress={()=>dispatch({type:'INCREMENT',payload:x.id})}><Text style={s.qty}>+</Text></Pressable></View></View>)}<Pressable onPress={()=>dispatch({type:'APPLY_PROMO',payload:'WELCOME10'})} style={[s.button,{backgroundColor:colors.accent}]}><Text style={s.buttonText}>Apply WELCOME10</Text></Pressable><Text style={[s.total,{color:colors.text}]}>Total: Rs. {state.items.reduce((a,x)=>a+x.price*x.quantity,0).toFixed(0)}</Text><Pressable onPress={checkout} style={[s.button,{backgroundColor:'#166534'}]}><Text style={s.buttonText}>Place Order</Text></Pressable></ScrollView>}
function Reserve({colors,reservations,setReservations}){const [date,setDate]=useState('2026-09-30');const [time,setTime]=useState('19:00');const [party,setParty]=useState('2'); const submit=()=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||+party<1||+party>12){Alert.alert('Invalid reservation');return;}setReservations(v=>[{id:Date.now(),date,time,party,status:'Pending'},...v]);Alert.alert('Reservation created');};return <ScrollView contentContainerStyle={{padding:14}}><Header title="Reservations" colors={colors}/><Input label="Date (YYYY-MM-DD)" colors={colors} value={date} onChangeText={setDate}/><Input label="Time" colors={colors} value={time} onChangeText={setTime}/><Input label="Party size (1-12)" colors={colors} value={party} onChangeText={setParty} keyboardType="number-pad"/><Pressable onPress={submit} style={[s.button,{backgroundColor:colors.accent}]}><Text style={s.buttonText}>Reserve Table</Text></Pressable>{reservations.map(r=><View key={r.id} style={[s.card,{backgroundColor:colors.card,borderColor:colors.border}]}><Text style={{color:colors.text}}>{r.date} · {r.time} · {r.party} guests</Text><Text style={{color:colors.muted}}>{r.status}</Text></View>)}</ScrollView>}
function Orders({colors,orders}){return <ScrollView contentContainerStyle={{padding:14}}><Header title="Order Tracking" colors={colors}/>{orders.length===0?<Text style={{color:colors.muted}}>No orders yet. Add food and place an order.</Text>:orders.map(o=><View key={o.id} style={[s.card,{backgroundColor:colors.card,borderColor:colors.border}]}><Text style={[s.bold,{color:colors.text}]}>{o.id}</Text><Text style={{color:colors.accent,fontSize:18}}>{o.status}</Text><Text style={{color:colors.muted}}>Takeaway · Rs. {o.total.toFixed(0)}</Text><Text style={{color:colors.muted}}>Progress: {o.status==='Pending'?'1/4':o.status==='Preparing'?'2/4':o.status==='Ready'?'3/4':'4/4'}</Text></View>)}</ScrollView>}
function Dashboard({colors,orders,setOrders}){return <ScrollView contentContainerStyle={{padding:14}}><Header title="Manager Dashboard" colors={colors}/><Text style={{color:colors.text,marginBottom:10}}>Incoming Orders</Text>{orders.length===0?<Text style={{color:colors.muted}}>No incoming orders yet.</Text>:orders.map(o=><View key={o.id} style={[s.card,{backgroundColor:colors.card,borderColor:colors.border}]}><Text style={[s.bold,{color:colors.text}]}>{o.id} · {o.status}</Text><View style={s.chips}>{['Pending','Preparing','Ready','Served'].map(st=><Pressable key={st} onPress={()=>setOrders(v=>v.map(x=>x.id===o.id?{...x,status:st}:x))} style={[s.chip,{backgroundColor:colors.accent}]}><Text style={{color:'#fff'}}>{st}</Text></Pressable>)}</View></View>)}</ScrollView>}
function Profile({colors,user,isDark,toggle,logout}){return <ScrollView contentContainerStyle={{padding:14}}><Header title="Profile" colors={colors}/><View style={[s.card,{backgroundColor:colors.card,borderColor:colors.border}]}><Text style={[s.bold,{color:colors.text}]}>{user.name}</Text><Text style={{color:colors.muted}}>{user.email}</Text><Text style={{color:colors.muted}}>Role: {user.role}</Text></View><View style={s.row}><Text style={{color:colors.text}}>Dark theme</Text><Switch value={isDark} onValueChange={toggle}/></View><Pressable onPress={logout} style={[s.button,{backgroundColor:colors.danger}]}><Text style={s.buttonText}>Logout</Text></Pressable></ScrollView>}

export default function App(){return <AuthProvider><ThemeProvider><CartProvider>{useAppRoot()}</CartProvider></ThemeProvider></AuthProvider>}
function useAppRoot(){const {user}=useAuth(); return user?<MainApp/>:<Login/>}
const s=StyleSheet.create({safe:{flex:1},center:{padding:24,alignItems:'center',justifyContent:'center',flexGrow:1},logo:{fontSize:34,fontWeight:'800',marginBottom:8},h1:{fontSize:26,fontWeight:'800',marginBottom:20},h2:{fontSize:24,fontWeight:'800'},header:{padding:16,paddingTop:8},input:{borderWidth:1,borderRadius:10,padding:12,fontSize:16},button:{padding:14,borderRadius:10,alignItems:'center',marginVertical:8},buttonText:{color:'#fff',fontWeight:'800'},note:{fontSize:12,textAlign:'center',marginTop:16},row:{flexDirection:'row',alignItems:'center',marginVertical:8},role:{padding:10,borderWidth:1,borderRadius:8,marginRight:8},chips:{flexDirection:'row',flexWrap:'wrap',gap:6,marginVertical:8},chip:{paddingVertical:7,paddingHorizontal:10,borderRadius:18,borderWidth:1},card:{flexDirection:'row',padding:14,borderRadius:12,borderWidth:1,marginBottom:10,gap:10},bold:{fontSize:16,fontWeight:'800'},smallButton:{padding:8,borderRadius:8,marginTop:8},qty:{fontSize:24},total:{fontSize:22,fontWeight:'800',marginVertical:12},tabs:{height:68,borderTopWidth:1,flexDirection:'row',justifyContent:'space-around',alignItems:'center'},tab:{alignItems:'center',minWidth:60}});
